import { CheckCircle, ClipboardText, Fingerprint, Pulse, Siren, Warning } from "@phosphor-icons/react/dist/ssr";
import { notFound } from "next/navigation";
import CommandShell from "../../../src/CommandShell";
import IncidentActions from "../../../src/IncidentActions";
import { ensureSchema, findEvidenceSubmissions, findIncident, listContinuityRecords, listEvidenceTasks, listRecoveryActions, listReliabilityProbes } from "../../../src/db";

export const dynamic = "force-dynamic";

export default async function IncidentPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; await ensureSchema(); const incident = await findIncident(id); if (!incident) notFound();
  const [allTasks, submissions, allRecords, allProbes, recoveryActions] = await Promise.all([listEvidenceTasks(), findEvidenceSubmissions(incident.id), listContinuityRecords(), listReliabilityProbes(), listRecoveryActions(incident.id)]);
  const tasks = allTasks.filter((task) => task.incidentId === incident.id); const records = allRecords.filter((record) => record.incidentId === incident.id); const probes = incident.endpointUrl ? allProbes.filter((probe) => probe.endpointUrl === incident.endpointUrl) : [];
  const events = [{ type: "CLAIMED", title: "Incident opened", detail: incident.claim, at: incident.createdAt, icon: Warning }, ...probes.map((probe) => ({ type: "OBSERVED", title: `${probe.status} endpoint observation`, detail: `${probe.summary}${probe.statusCode ? ` · HTTP ${probe.statusCode}` : ""}`, at: probe.completedAt, icon: Pulse })), ...recoveryActions.map((action) => ({type:"RECOVERED",title:`${action.actionType.replaceAll("_"," ")} ${action.status.toLowerCase()}`,detail:action.detail,at:action.completedAt??action.startedAt,icon:CheckCircle})), ...tasks.map((task) => ({ type: "REQUESTED", title: `${task.taskType.replaceAll("_", " ")} evidence task`, detail: `${task.assignmentStatus} · deadline ${new Date(task.deadline).toLocaleString()}`, at: task.createdAt, icon: Fingerprint })), ...submissions.map((submission) => ({ type: submission.reviewStatus === "ACCEPTED" ? "VERIFIED" : "SUBMITTED", title: `${submission.reviewStatus} signed observation`, detail: submission.statement, at: submission.reviewedAt ?? submission.createdAt, icon: CheckCircle })), ...records.map((record) => ({ type: "RECORDED", title: `${record.verdict.replaceAll("_", " ")} record issued`, detail: `${record.confidence} confidence · ${record.recordHash.slice(0, 16)}…`, at: record.createdAt, icon: ClipboardText }))].sort((a, b) => Date.parse(a.at) - Date.parse(b.at));
  return <CommandShell current=""><section className="incident-command-header"><div><p className="kicker">{incident.publicSlug} / INCIDENT COMMAND</p><h1>{incident.agentName}</h1><p>{incident.claim}</p></div><div className="incident-status-block"><Siren aria-hidden="true" /><strong>{incident.status}</strong><span className={`severity severity-${incident.severity.toLowerCase()}`}>{incident.severity}</span></div></section><section className="incident-facts"><div><span>Incident type</span><strong>{incident.incidentType.replaceAll("_", " ")}</strong></div><div><span>Requested outcome</span><strong>{incident.requestedOutcome.replaceAll("_", " ")}</strong></div><div><span>Opened by</span><strong>{incident.openedBy}</strong></div><div><span>Target</span><strong>{incident.endpointUrl ?? "No endpoint declared"}</strong></div></section><div className="incident-command-grid"><section className="timeline-panel"><header className="section-title"><div><p className="kicker">OPERATIONAL TIMELINE</p><h2>Observed, claimed, verified</h2></div><span>{events.length} persisted events</span></header><ol className="incident-timeline">{events.map((event, index) => { const Icon = event.icon; return <li key={`${event.at}-${index}`}><span className={`timeline-icon timeline-${event.type.toLowerCase()}`}><Icon aria-hidden="true" /></span><div><header><strong>{event.title}</strong><span>{event.type}</span></header><p>{event.detail}</p><time>{new Date(event.at).toLocaleString()}</time></div></li>; })}</ol></section><IncidentActions incidentId={incident.id} endpointUrl={incident.endpointUrl} agentName={incident.agentName} /></div></CommandShell>;
}
