import { CheckCircle, Fingerprint, HashStraight, SealCheck } from "@phosphor-icons/react/dist/ssr";
import { notFound } from "next/navigation";
import ShareRecordButton from "../../../src/ShareRecordButton";
import { ensureSchema, findContinuityRecord } from "../../../src/db";

export const dynamic = "force-dynamic";

export default async function ContinuityRecordPage({ params }: { params: Promise<{ recordId: string }> }) {
  const { recordId } = await params; await ensureSchema(); const record = await findContinuityRecord(recordId); if (!record) notFound(); const evidence = record.evidenceSummary;
  return <main className="public-record" id="main-content"><header className="public-record-nav"><a href="/">CONTINUITY / COMMAND</a><span>PUBLIC RECOVERY RECORD</span></header><article className="public-record-sheet"><header><div><p className="kicker">INCIDENT OUTPUT / SHA-256 SEALED</p><h1>{record.agentName}</h1><p>{record.recordType.replaceAll("_", " ")} · issued {new Date(record.createdAt).toLocaleString()}</p></div><div className={`record-verdict verdict-${record.verdict.toLowerCase()}`}><SealCheck aria-hidden="true" /><strong>{record.verdict.replaceAll("_", " ")}</strong><span>{record.confidence} CONFIDENCE</span></div></header><section className="record-statement"><p>“{record.impactSummary}”</p><span>Incident impact preserved as submitted</span></section><div className="record-columns"><section><p className="kicker">ASSESSMENT</p><h2>What the record can support</h2><p>{record.rootCause}</p></section><section className="evidence-meter"><p className="kicker">EVIDENCE STATE</p><div><span><strong>{String(evidence.totalSubmissions ?? 0)}</strong>Submitted</span><span><strong>{String(evidence.acceptedSubmissions ?? 0)}</strong>Accepted</span><span><strong>{String(evidence.pendingSubmissions ?? 0)}</strong>Pending</span></div></section></div><div className="record-columns lower"><section><p className="kicker">SIGNED VERIFIERS</p>{Array.isArray(evidence.signedVerifiers) && evidence.signedVerifiers.length ? <div className="verifier-list">{evidence.signedVerifiers.map((wallet) => <code key={String(wallet)}><Fingerprint aria-hidden="true" />{String(wallet)}</code>)}</div> : <p className="record-empty">No accepted signed verifier is included. The record remains explicit about that absence.</p>}</section><section><p className="kicker">NEXT SAFE ACTION</p><ol className="record-actions">{record.recommendedActions.map((action) => <li key={action}><CheckCircle aria-hidden="true" />{action}</li>)}</ol></section></div><div className="record-hash"><HashStraight aria-hidden="true" /><div><span>RECORD HASH / SHA-256</span><code>{record.recordHash}</code></div></div><footer><div><strong>OBSERVED ≠ CLAIMED ≠ VERIFIED</strong><span>Continuity preserves the boundary.</span></div><ShareRecordButton agentName={record.agentName} verdict={record.verdict} /></footer><details className="machine-record"><summary>Inspect machine-readable record</summary><pre>{JSON.stringify(record, null, 2)}</pre></details></article></main>;
}
