"use client";

import { ArrowLeft, ArrowRight, CheckCircle, Pulse, WarningCircle } from "@phosphor-icons/react";
import { useState } from "react";

type ProbeResult = { probeId: string; status: string; summary: string; http: { statusCode: number | null; latencyMs: number | null; contentType: string | null } };

export default function AgentOnboardingForm() {
  const [agentName, setAgentName] = useState(""); const [endpointUrl, setEndpointUrl] = useState(""); const [expectedStatus, setExpectedStatus] = useState("200"); const [expectedContentType, setExpectedContentType] = useState("application/json"); const [intervalSeconds, setIntervalSeconds] = useState("60"); const [recoveryPolicy, setRecoveryPolicy] = useState("RETRY_AND_ESCALATE"); const [result, setResult] = useState<ProbeResult | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function connect() { setBusy(true); setError(null); try { const registration={agentName:agentName.trim(),endpointUrl:endpointUrl.trim(),expectedStatus:Number(expectedStatus),expectedContentType:expectedContentType.trim(),intervalSeconds:Number(intervalSeconds),recoveryPolicy}; const registered=await fetch("/api/v1/agents",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(registration)});const registeredBody=await registered.json();if(!registered.ok)throw new Error(registeredBody.error??"The agent could not be registered."); const response = await fetch("/api/v1/check-agent-status", { method:"POST", headers:{"content-type":"application/json"}, body:JSON.stringify({ ...registration, timeoutMs:8000 }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "The first endpoint observation failed."); setResult(body); } catch (reason) { setError(reason instanceof Error ? reason.message : "The endpoint could not be added."); } finally { setBusy(false); } }
  if (result) return <section className="onboarding-card onboarding-success"><CheckCircle /><span>Agent connected</span><h2>{agentName}</h2><p>{result.summary}</p><dl><div><dt>Status</dt><dd>{result.status}</dd></div><div><dt>HTTP status</dt><dd>{result.http.statusCode ?? "—"}</dd></div><div><dt>Latency</dt><dd>{result.http.latencyMs ?? "—"} ms</dd></div><div><dt>Probe ID</dt><dd><code>{result.probeId}</code></dd></div></dl><a className="button-primary" href="/">Return to overview <ArrowRight /></a></section>;
  return <form className="onboarding-card" onSubmit={(event) => { event.preventDefault(); void connect(); }}><header><Pulse /><div><h2>Autonomy contract</h2><p>Declare what Continuity should observe and what it may do.</p></div></header>{error ? <div className="form-error" role="alert"><WarningCircle />{error}</div> : null}<label><span>Agent name</span><input required value={agentName} onChange={(event) => setAgentName(event.target.value)} placeholder="e.g. Research coordinator" /></label><label><span>HTTPS endpoint</span><input required type="url" value={endpointUrl} onChange={(event) => setEndpointUrl(event.target.value)} placeholder="https://agent.example.com/health" /></label><div className="form-row"><label><span>Expected status</span><input required type="number" min="100" max="599" value={expectedStatus} onChange={(event) => setExpectedStatus(event.target.value)} /></label><label><span>Expected content type</span><input required value={expectedContentType} onChange={(event) => setExpectedContentType(event.target.value)} /></label></div><div className="form-row"><label><span>Check interval</span><select value={intervalSeconds} onChange={(event)=>setIntervalSeconds(event.target.value)}><option value="60">Every minute</option><option value="300">Every 5 minutes</option><option value="900">Every 15 minutes</option><option value="3600">Every hour</option></select></label><label><span>Recovery policy</span><select value={recoveryPolicy} onChange={(event)=>setRecoveryPolicy(event.target.value)}><option value="RETRY_AND_ESCALATE">Retry and escalate</option><option value="OBSERVE_ONLY">Observe only</option><option value="AUTO_RECOVER">Automatic recovery</option></select></label></div><p className="policy-note">Automatic recovery runs only when a compatible adapter exists. Every action is persisted and followed by a fresh contract check.</p><footer><a className="button-secondary" href="/"><ArrowLeft />Cancel</a><button className="button-primary" disabled={busy || !agentName.trim() || !endpointUrl.trim()}>{busy ? "Registering agent…" : "Register autonomous monitor"}<ArrowRight /></button></footer></form>;
}
