"use client";

import { ArrowRight, ClipboardText, Fingerprint, Pulse } from "@phosphor-icons/react";
import { useState } from "react";

export default function IncidentActions({ incidentId, endpointUrl, agentName }: { incidentId: string; endpointUrl: string | null; agentName: string }) {
  const [busy, setBusy] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [taskId, setTaskId] = useState<string | null>(null); const [recordId, setRecordId] = useState<string | null>(null);
  async function post(path: string, body: Record<string, unknown>) { const response = await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(typeof result.error === "string" ? result.error : "Action failed."); return result; }
  async function execute(name: string, action: () => Promise<void>) { setBusy(name); setMessage(null); try { await action(); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "Action failed."); } finally { setBusy(null); } }
  return <section className="incident-actions"><header><p className="kicker">RESPONSE CONSOLE</p><h2>Choose the next safe action</h2></header><div>{endpointUrl ? <button className="action-control" disabled={busy !== null} onClick={() => void execute("probe", async () => { const result = await post("/api/v1/check-agent-status", { agentName, endpointUrl, expectedStatus: 200, expectedContentType: "application/json", timeoutMs: 8000 }); setMessage(`Probe persisted: ${String(result.status)} · ${String(result.probeId)}`); })}><Pulse /><span><strong>Run follow-up probe</strong><small>Observe the endpoint again</small></span><ArrowRight /></button> : null}<button className="action-control" disabled={busy !== null} onClick={() => void execute("task", async () => { const result = await post("/api/v1/request-human-evidence", { incidentId, taskType: "MANUAL_QA", instructions: "Observe the incident target and sign only the facts you can directly verify.", rewardAmount: "0", rewardToken: "USDT0", deadlineMinutes: 120 }); setTaskId(String(result.taskId)); setMessage("Evidence task created with zero payment."); })}><Fingerprint /><span><strong>Request signed evidence</strong><small>Create a no-gas verifier task</small></span><ArrowRight /></button><button className="action-control" disabled={busy !== null} onClick={() => void execute("record", async () => { const result = await post("/api/v1/issue-continuity-record", { incidentId, recordType: "INCIDENT_RECORD" }); setRecordId(String(result.recordId)); setMessage(`Record issued: ${String(result.verdict)} / ${String(result.confidence)}`); })}><ClipboardText /><span><strong>Issue current record</strong><small>Preserve the evidence state now</small></span><ArrowRight /></button></div>{busy ? <p className="action-message">Executing {busy}…</p> : message ? <p className="action-message">{message}</p> : null}{taskId ? <a className="action-followup" href={`/evidence-tasks/${taskId}`}>Open verifier task <ArrowRight /></a> : null}{recordId ? <a className="action-followup" href={`/records/${recordId}`}>Reveal issued record <ArrowRight /></a> : null}</section>;
}
